spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emailprojectback;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: caneta11
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
  api-docs:
    enabled: true
