spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/emailprojectback
    password: caneta11
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
